### PR TITLE
Fix intra-file comment ordering in aggregated comments

### LINKED ISSUE #132: When posting aggregated comment, group issues by reported, sort issues by file name, then sort issues by line number.
Currently, line numbers are not reported in order which is confusing to read:

screen shot 2016-11-08 at 8 43 11 am

### PR DESCRIPTION
**Pull request by stkent**
Fixes #132 

`master` allows weird ordering, for example see https://github.com/stkent/gnag-testing/pull/2#issuecomment-230483971.

Now the ordering is fixed, for example see https://github.com/stkent/gnag-testing/pull/2#issuecomment-259329795.

The order in which individual comments are posted to GitHub should be unchanged.

### CODE REVIEW

File: plugin/src/main/groovy/com/btkelly/gnag/models/Violation.java [hunk 1]
```diff
@@ -24,25 +24,38 @@
...
 
-        if (v1RelativeFilePath.equals(v2RelativeFilePath)) {
-            return v1.getFileLineNumber().compareTo(v2.getFileLineNumber());
+        final Integer v1FileLineNumber = v1.getFileLineNumber();
+        final Integer v2FileLineNumber = v2.getFileLineNumber();
+
+        if (v1FileLineNumber == null && v2FileLineNumber == null) {
+            return 0;
+        } else if (v1FileLineNumber == null) {
+            return -1;
```
Comment (stkent) [inline plugin/src/main/groovy/com/btkelly/gnag/models/Violation.java]: Oops, think I need to flip this. -1 implies v1 < v2 which would sort it earlier in the list, not later. Willfix!

**Comment by btkelly** [comment]
👍
